# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_reviewer_app', '0003_auto_20180129_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='names',
            new_name='name',
        ),
    ]
