# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-26 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_users_app', '0005_auto_20180126_0629'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
