# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 02:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='First name must be entered more than 3 characters or more', regex='[a-ZA-Z]{3}')]),
        ),
    ]
